from django.db import models
from datetime import date

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=40)
    age = models.PositiveIntegerField()
    age_group = models.CharField(max_length=20, default="No age group")

    def __str__(self):
        return f'Name: {self.name}'

# Custom migration

# Generated by Django 4.2 on 2024-06-27 14:22

from django.db import migrations


def update_age_group(apps, schema_editor):
    Person = apps.get_model("main_app", "Person")
    all_persons = Person.objects.all()

    updated_persons = []

    for curr_person in all_persons:
        if curr_person.age <= 12:
            curr_person.age_group = 'Child'
        elif curr_person.age >= 13 and curr_person.age <= 17:
            curr_person.age_group = 'Teen'
        else:
            curr_person.age_group = 'Adult'

        updated_persons.append(curr_person)

    Person.objects.bulk_update(updated_persons, ['age_group'])


def reverse_age_group(apps, schema_editor):
    Person = apps.get_model("main_app", "Person")
    all_persons = Person.objects.all()

    updated_persons = []

    for curr_person in all_persons:
        curr_person.age_group = 'No age group'
        updated_persons.append(curr_person)

    Person.objects.bulk_update(updated_persons, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(update_age_group, reverse_age_group)
    ]
