from django.db import models
from datetime import date

# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    rarity = models.CharField(max_length=20, default='No rarity')

# After the migration of Item model, create an empty migration with the below code
# Generated by Django 4.2 on 2024-06-28 21:05

from django.db import migrations


def change_rarity(num):
    if num <= 10:
        return 'Rare'
    elif 11 <= num <= 20:
        return 'Very Rare'
    elif 21 <= num <= 30:
        return 'Extremely Rare'
    else:
        return 'Mega Rare'


def update_rarity(apps, schema_editor):
    item = apps.get_model("main_app", "Item")
    all_items = item.objects.all()

    update_items = []

    for curr_item in all_items:
        curr_item.rarity = change_rarity(float(curr_item.price))
        update_items.append(curr_item)

    item.objects.bulk_update(update_items, ['rarity'])


def reverse_rarity(apps, schema_editor):
    item = apps.get_model("main_app", "Item")
    all_items = item.objects.all()

    update_items = []

    for curr_item in all_items:
        curr_item.rarity = 'No rarity'
        update_items.append(curr_item)

    item.objects.bulk_update(update_items, ['rarity'])



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(update_rarity, reverse_rarity)
    ]